---

- name: Include OS-specific tasks
  include_tasks: "{{ os_item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
  become: 'yes'
  loop_control:
    loop_var: os_item
