---

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install GPG key
  apt_key:
    url: "{{ gitlab_gpg_key_url }}"
    id: "{{ gitlab_gpg_key_id }}"
    state: present

- name: Install APT repository
  apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ {{ ansible_distribution_release|lower }} main"
    update_cache: yes
    state: present

#- name: Install GitLab
#  package:
#    name: "gitlab={{ docker_version }}~ce-0~ubuntu"
#    state: present
#  notify: Restart gitlab 
